config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root to: 'products#search'
  get 'products/search'
  post 'products/search'

  post 'products/get'

  post 'products/record'
  post 'products/download'

  get 'products/setup'
  post 'products/setup'

  post 'products/regist'

  post 'products/delete'

  mount Resque::Server.new, at: "/resque"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/sign_in' => 'devise/sessions#new'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  require 'uri'
  require 'open-uri'
  require 'nokogiri'
  require 'date'

  def collect(user, data)
    logger.debug("====== Collect ========")
    asin = data[0]
    logger.debug(asin)
    check1 = data[9].to_s
    check2 = data[14].to_s
    check3 = data[18].to_s
    logger.debug(check1)
    logger.debug(check2)
    logger.debug(check3)

    url = 'https://delta-tracer.com/item/chart_html/jp/' + asin

    charset = nil
    begin
      html = open(url) do |f|
        charset = f.charset
        f.read # htmlを読み込んで変数htmlに渡す
      end
    rescue OpenURI::HTTPError => error
      logger.debug("===== ERROR =====")
      logger.debug(error)

      hit = Product.where(user: user).find_or_create_by(asin: asin)

      result = {
        asin: asin,
        new_sale1: 0,
        new_sale2: 0,
        new_sale3: 0,
        used_sale1: 0,
        used_sale2: 0,
        used_sale3: 0,
        new_avg3: 0,
        used_avg3: 0,
        check1: check1,
        cart_price: 0,
        cart_income: 0,
        used_price: 0,
        used_income: 0,
        check2: check2,
        title: "※該当商品なし",
        mpn: "",
        item_image: "",
        check3: check3,
        new_bid_price: 0,
        used_bid_price: 0,
        new_negotiate_price: 0,
        used_negotiate_price: 0
      }
      hit.update(result)

      return result

    end

    json = html.match(/JSON.parse\('([\s\S]*?)'/)[1]
    rawdata = JSON.parse(json)

    timestamp = rawdata['timestamp']
    new_count = rawdata['data']['new_count']
    used_count = rawdata['data']['used_count']
    sales_rank = rawdata['data']['sales_rank']

    new_counter1 = 0
    new_counter2 = 0
    new_counter3 = 0

    used_counter1 = 0
    used_counter2 = 0
    used_counter3 = 0

    counter1 = 0
    counter2 = 0
    counter3 = 0

    d1 = 1.months.ago.to_i * 1000
    d2 = 2.months.ago.to_i * 1000
    d3 = 3.months.ago.to_i * 1000

    timestamp.each.with_index(1)  do |tt, j|

      diff = sales_rank[j].to_i - sales_rank[j-1].to_i
      new_diff = new_count[j].to_i - new_count[j-1].to_i
      used_diff = used_count[j].to_i - used_count[j-1].to_i

      if diff < (sales_rank[j-1].to_i*0.05*(-1)) then
        if tt > d3 then
          if new_diff < 0 then
            new_counter3 += 1
          end
          if used_diff < 0 then
            used_counter3 += 1
          end
          counter3 += 1

          if tt > d2 then
            if new_diff < 0 then
              new_counter2 += 1
            end
            if used_diff < 0 then
              used_counter2 += 1
            end
            counter2 += 1

            if tt > d1 then
              if new_diff < 0 then
                new_counter1 += 1
              end
              if used_diff < 0 then
                used_counter1 += 1
              end
              counter1 += 1
            end
          end
        end
      end
    end

    avg_new = (new_counter3) / 3
    if new_counter3 > 0 && avg_new == 0 then
      avg_new = 1
    end
    avg_used = (used_counter3) / 3

    puts '===== VALUES ======'
    puts "avg_new=" + avg_new.to_s
    puts "avg_used=" + avg_used.to_s
    puts "new_counter1=" + new_counter1.to_s
    puts "new_counter2=" + new_counter2.to_s
    puts "new_counter3=" + new_counter3.to_s
    puts "used_counter1=" + used_counter1.to_s
    puts "used_counter2=" + used_counter2.to_s
    puts "used_counter3=" + used_counter3.to_s
    puts '===== END ======'

    if avg_new == 0 && avg_used == 0 then
      puts '===== NO DATA ======'
      hit = Product.where(user: user).find_or_create_by(asin: asin)

      result = {
        asin: asin,
        new_sale1: 0,
        new_sale2: 0,
        new_sale3: 0,
        used_sale1: 0,
        used_sale2: 0,
        used_sale3: 0,
        new_avg3: 0,
        used_avg3: 0,
        check1: check1,
        cart_price: 0,
        cart_income: 0,
        used_price: 0,
        used_income: 0,
        check2: check2,
        title: "※該当データなし",
        mpn: "",
        item_image: "",
        check3: check3,
        new_bid_price: 0,
        used_bid_price: 0,
        new_negotiate_price: 0,
        used_negotiate_price: 0
      }
      hit.update(result)

      return result
    end

    url = "https://delta-tracer.com/item/detail/jp/" + asin
    charset = nil
    html = nil
    begin
      html = open(url) do |f|
        charset = f.charset
        f.read # htmlを読み込んで変数htmlに渡す
      end
    rescue OpenURI::HTTPError => error
      logger.debug("===== ERROR =====")
      logger.debug(error)
    end

    cart = html.match(/新品カート<\/strong>([\s\S]*?)<\/tr>/)
    if cart != nil then
      cart = cart[1]
      cart = cart.scan(/<strong>([\s\S]*?)<\/strong>/)
      if cart != nil then
        if cart[0] != nil then
          cart_price = cart[0][0].gsub(",","").to_i
          if cart[1] != nil then
            cart_profit = cart[1][0].gsub(",","").to_i
          else
            cart_profit = 0
          end
        else
          cart_price = 0
          cart_profit = 0
        end
      else
        cart_price = 0
        cart_profit = 0
      end
    else
      cart_price = 0
      cart_profit = 0
    end

    used = html.match(/中古<\/strong>([\s\S]*?)<\/tr>/)
    if used != nil then
      used = used[1]
      used = used.scan(/<strong>([\s\S]*?)<\/strong>/)
      if used != nil then
        if used[0] != nil then
          used_price = used[0][0].gsub(",","").to_i
          if used[1] != nil then
            used_profit = used[1][0].gsub(",","").to_i
          else
            used_profit = 0
          end
        else
          used_price = 0
          used_profit = 0
        end
      else
        used_price = 0
        used_profit = 0
      end
    else
      used_price = 0
      used_profit = 0
    end

    title = html.match(/<strong style="word-break:break-all;">([\s\S]*?)<\/strong>/)
    if title != nil then
      title = title[1]
      mpn = html.match(/<strong>規格番号：<\/strong><input class="selectable" value="([\s\S]*?)"/)
      if mpn != nil then
        mpn = mpn[1]
      else
        mpn = ""
      end

      temp = html.match(/<table class="table-itemlist"([\s\S]*?)td>/)
      if temp != nil then
        temp = temp[1]
        image = temp.match(/src="([\s\S]*?)"/)
        if image != nil then
          image = image[1]
        else
          image = ""
        end
      else
        image = ""
      end

      if check1 == "true" then
        cart_price = data[11].to_i
        cart_profit = data[12].to_i
        used_price = data[13].to_i
        used_profit = data[14].to_i
      end

      logger.debug(cart_price)
      logger.debug(cart_profit)
      logger.debug(used_price)
      logger.debug(used_profit)

      #計算
      tuser = Account.find_by(user: user)
      profit_rate = (tuser.profit_rate.to_f / 100.to_f).to_f
      used_profit_rate = (tuser.used_profit_rate.to_f / 100.to_f).to_f
      shipping = tuser.shipping

      puts profit_rate
      puts shipping

      if cart_price != 0 then
        new_bid_price = cart_profit.to_f - shipping.to_f - (cart_price.to_f * profit_rate).to_f
        new_bid_price = new_bid_price.round(-2)

        if cart_profit * (1.to_f - profit_rate).to_f < 10000 then
          temp = cart_profit.to_f * (1.to_f - profit_rate).to_f
          new_negotiate_price = (temp.to_i / 500.to_i) * 500
        else
          temp = cart_profit.to_f * (1.to_f - profit_rate).to_f
          new_negotiate_price = (temp.to_i / 1000.to_i) * 1000
        end
      else
        new_bid_price = 0
        new_negotiate_price = 0
      end

      if used_price != 0 then
        used_bid_price = used_profit.to_f - shipping.to_f - (used_price.to_f * used_profit_rate).to_f
        used_bid_price = used_bid_price.round(-2)

        if used_profit * (1.to_f - used_profit_rate).to_f < 10000 then
          temp = used_profit.to_f * (1.to_f - used_profit_rate).to_f
          used_negotiate_price = (temp.to_i / 500.to_i) * 500
        else
          temp = used_profit.to_f * (1.to_f - used_profit_rate).to_f
          used_negotiate_price = (temp.to_i / 1000.to_i) * 1000
        end

      else
        used_bid_price = 0
        used_negotiate_price = 0
      end
    else
      title = ""
      mpn = ""
      image = ""
    end

    puts '===== VALUES ======'
    puts "title=" + title.to_s
    puts "mpn=" + mpn.to_s
    puts "image=" + image.to_s
    puts "cart_price=" + cart_price.to_s
    puts "cart_profit=" + cart_profit.to_s
    puts "used_price=" + used_price.to_s
    puts "used_profit=" + used_profit.to_s
    puts '===== END ======'

    hit = Product.where(user: user).find_or_create_by(asin: asin)

    if check1 == "true" then
      logger.debug("check1")
      cart_price = data[10].to_i
      cart_income = data[11].to_i
      used_price = data[12].to_i
      used_income = data[13].to_i
    end

    if check2 == "true" then
      logger.debug("check2")
      title = data[15].to_s
      mpn = data[16].to_s
      image = /src="([\s\S]*?)"/.match(data[17])[1]
    end

    if check3 == "true" then
      logger.debug("check3")
      new_bid_price = data[19].to_i
      used_bid_price = data[20].to_i
      new_negotiate_price = data[21].to_i
      used_negotiate_price = data[22].to_i
    end

    used_counter3 = used_counter3 - used_counter2
    used_counter2 = used_counter2 - used_counter1
    new_counter3 = counter3 - counter2 - used_counter3
    new_counter2 = counter2 - counter1 - used_counter2
    new_counter1 = counter1 - used_counter1

    avg_new = (new_counter3 + new_counter2 + new_counter1) / 3

    result = {
      asin: asin,
      new_sale1: new_counter1,
      new_sale2: new_counter2,
      new_sale3: new_counter3,
      used_sale1: used_counter1,
      used_sale2: used_counter2,
      used_sale3: used_counter3,
      new_avg3: avg_new,
      used_avg3: avg_used,
      check1: check1,
      cart_price: cart_price,
      cart_income: cart_profit,
      used_price: used_price,
      used_income: used_profit,

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  require 'nokogiri'
  require 'uri'
  require 'csv'
  require 'peddler'
  require 'typhoeus'
  require 'date'
  require 'kconv'
  require 'activerecord-import'

  before_action :authenticate_user!, :except => [:regist]
  protect_from_forgery :except => [:regist]

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def search
    @limit = ENV['MAX_ROWNUM']
    if @limit == nil then @limit = 1000 end
    logger.debug(@limit)
    @login_user = current_user
    @account = Account.find_or_create_by(user: current_user.email)
    @products = Product.where(user: current_user.email)
    if @products == nil then
      @products = Product.create(user: current_user.email)
    end
    @header = Product.column_names
    @header = [
      "asin",
      "new_sale1",
      "new_sale2",
      "new_sale3",
      "new_avg3",
      "used_sale1",
      "used_sale2",
      "used_sale3",
      "used_avg3",
      "check1",
      "cart_price",
      "cart_income",
      "used_price",
      "used_income",
      "check2",
      "title",
      "mpn",
      "item_image",
      "check3",
      "new_bid_price",
      "used_bid_price",
      "new_negotiate_price",
      "used_negotiate_price"
    ]

    if request.post? then
      logger.debug("post")
      res = 'no data'

      render json: ['no data']
    else
      logger.debug("other")
    end
  end


  def get
    if request.post? then
      body = params[:data]
      #rnum = params[:rnum].to_i
      res = JSON.parse(body)
      #logger.debug(res)
      user = current_user.email
      #data = res[rnum]
      data = res
      logger.debug("==== Get Start ====")
      logger.debug(data)
      #logger.debug(rnum)
      logger.debug("==== ==== ====")

      temp = Product.new
      result = temp.collect(user, data)

      render json: result
    else
      logger.debug("other")
    end
  end

  def record
    if request.post? then
      products = Product.where(user: current_user.email)
      body = params[:data]
      head =params[:header]
      body = JSON.parse(body)
      head = JSON.parse(head)
      logger.debug("====== BODY =======")
      logger.debug(body)
      logger.debug("====== HEAD =======")
      logger.debug(head)

      products.delete_all

      body.each do |row|
        if row[0] != "" then

          thash = Hash.new
          i = 0
          head.each_key do |key|
            if key != "item_image" then
              thash[key] = row[i]
            else
              thash[key] = /src="([\s\S]*?)"/.match(row[i])[1]
            end
            i += 1
          end
          logger.debug("====== HASH =======")
          logger.debug(thash)
          target = products.find_or_create_by(asin: row[0])
          if target != nil then
            target.update(thash)
          end
        end
      end

      render json: ["ok"]
    end
  end


  def setup
    @login_user = current_user
    @account = Account.find_or_create_by(user:current_user.email)
    if request.post? then
      @account.update(user_params)
    end
  end


  def delete
    @login_user = current_user
    temp = Product.where(user: current_user.email)
    if request.post? then
      temp.delete_all
    end
    render json: ["ok"]
  end

  def regist
    if request.post? then
      user = params[:user]
      password = params[:password]
      logger.debug("====== Regist from Form =======")
      logger.debug(user)
      logger.debug(password)
      tuser = User.find_or_initialize_by(email: user)
      if tuser.new_record? # 新規作成の場合は保存
        tuser = User.create(email: user, password: password)
      end
      Account.find_or_create_by(user: user)
      logger.debug("====== Regist from Form End =======")
    end
    redirect_to products_search_path
  end

  def download
    if request.post? then
      body = params[:data]
      @data = JSON.parse(body)
      respond_to do |format|
        format.html do
        end
        format.csv do
          logger.debug("csv")
          tt = Time.now
          strTime = tt.strftime("%Y%m%d%H%M")
          fname = "商品データ_" + strTime + ".csv"
          #send_data render_to_string, filename: fname, type: :csv
          render render_to_string, filename: fname, type: :csv
        end
      end
    end

  end

  private
  def user_params
     params.require(:account).permit(:user, :seller_id, :mws_auth_token, :profit_rate, :shipping, :used_profit_rate)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/search.html.erb
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-12 col-md-12">
      <h3>商品情報を取得</h3>
        <button id="run_search" class="btn btn-primary" style="margin-right: 20px;">取得開始</button>
        <button id="update_data" class="btn btn-primary" style="margin-right: 20px;">データ更新</button>
        <button id="delete_data" class="btn btn-primary" style="margin-right: 20px;">一括削除</button>
        <button id="csv_download" class="btn btn-info" style="margin-right: 20px;">CSVダウンロード</button>
        <a style="display:none;" id="downloader" href="#"></a>
      <div><br></div>
      <div id="result_table"></div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    // create table for ASIN
    var convh = {
      "asin": "ASIN",
      "new_sale1" : "新品過去1ヶ月",
      "new_sale2" : "新品過去2ヶ月",
      "new_sale3" : "新品過去3ヶ月",
      "new_avg3" : "新品3ヶ月平均",
      "used_sale1" : "中古過去1ヶ月",
      "used_sale2" : "中古過去2ヶ月",
      "used_sale3" : "中古過去3ヶ月",
      "used_avg3" : "中古3ヶ月平均",
      "check1" : "チェック1",
      "cart_price" : "カート価格",
      "cart_income" : "カート入金",
      "used_price" : "中古最安値",
      "used_income" : "中古入金",
      "check2" : "チェック2",
      "title" : "商品名",
      "mpn" : "型番",
      "item_image" : "商品画像",
      "check3" : "チェック3",
      "new_bid_price" : "新品入札価格",
      "used_bid_price" : "中古入札価格",
      "new_negotiate_price" : "新品交渉価格",
      "used_negotiate_price" : "中古交渉価格"
    }
    var cheaders = [];
    var cwidth = [];
    var mydata = [];
    var colOption = [];
    <% data = Array.new %>
    <% jj = 0 %>
    <% @header.each_with_index do |name, i| %>
        cheaders.push(convh["<%= name %>"]);
        cwidth.push(120);
        <% if i == 9 || i == 14 || i == 18 then %>
          colOption.push({className: "htCenter htMiddle", type:"checkbox", uncheckedTemplate: null});
        <% elsif i == 17 then %>
          colOption.push({className: "htCenter htMiddle", renderer: 'html'});
        <% else %>
          colOption.push({className: "htCenter htMiddle"});
        <% end %>
        <% data.push(@products.pluck(name)) %>

    <% end %>

    cwidth[9] = 90;
    cwidth[10] = 90;
    cwidth[11] = 90;
    cwidth[12] = 90;
    cwidth[13] = 90;
    cwidth[14] = 90;
    cwidth[15] = 280;
    cwidth[17] = 100;
    <% data = data.transpose %>

    var maxColnum = cheaders.length;
    var maxRownum = 5000;
    var limit = <%= @limit %>;
    if(limit != null){
      if(maxRownum < limit){
        maxRownum = limit;
      }
    }

    <% data.each_with_index do |row, ii| %>
      mydata[<%= ii %>] = [];
      <% row.each_with_index do |col, jj| %>
        mydata[<%= ii %>][<%= jj %>] = "<%= col %>";
        <% if jj == 17 then %>
          mydata[<%= ii %>][<%= jj %>] = '<img src="<%= col %>" height="40" >';
        <% end %>
      <% end %>
    <% end %>

    for(var k = <%= data.length %>; k < <%= data.length %> + 5000; k++){
      mydata[k] = [];
      for(var m = 0; m < cheaders.length; m++){
        mydata[k][m] = "";
      }
    }

    var container = document.getElementById('result_table');
    var handsontable = new Handsontable(container, {
      /* オプション */
      width: 1140,
      height: 600,
      contextMenu: true,
      data: mydata,
      rowHeaders: true,
      colHeaders: cheaders,
      maxCols: maxColnum,
      maxRows: maxRownum,
      manualColumnResize: true,
      autoColumnSize: false,
      colWidths: cwidth,
      rowHeights: 60,
      wordWrap: false,
      columnSorting: true,
      columns: colOption
    });

    $("#update_data").click(function () {
      alert("record");
      var body = handsontable.getData();
      var head = convh;
      body = JSON.stringify(body);
      head = JSON.stringify(head);
      var myData = {data: body, header: head};
      $.ajax({
        url: "/products/record",
        type: "POST",
        data: myData,
        dataType: "json",
        success: function (result) {
          //mydata[rnum] = result;
          console.log("start");
          var cheaders = Object.keys(convh);
          var temp = [];
          alert("Update");
        },
        error: function () {
          alert("NG");
        }
      });

    });

    $("#run_search").click(function () {
      alert("Start");
      var body = handsontable.getData();
      body = JSON.stringify(body);
      var rnum = 0;
      repeat(rnum);
    });

    function repeat(rnum){
      //var org = handsontable.getData();
      var org = handsontable.getDataAtRow(rnum);
      body = JSON.stringify(org);
      //var myData = {data: body, rnum: rnum};
      var myData = {data: body};

      $.ajax({
        url: "/products/get",
        type: "POST",
        data: myData,
        dataType: "json",
        success: function (result) {
          //mydata[rnum] = result;
          console.log("start");
          var cheaders = Object.keys(convh);
          var temp = [];
          console.log(result);
          for(var k = 0; k < cheaders.length; k++){
            console.log(cheaders[k]);
            console.log(result[cheaders[k]]);
            temp[k] = [];
            if(cheaders[k] == "item_image"){
              temp[k] = [rnum, k, '<img src="' + result[cheaders[k]] + '" height="40">'];
            }else{
              temp[k] = [rnum, k, result[cheaders[k]]];
            }
          }
          console.log("===========");
          console.log(rnum);
          handsontable.setDataAtCell(temp);
          handsontable.render();
          console.log("end");
          rnum++;
          org = handsontable.getDataAtRow(rnum);
          if(org[0] == ""){
            alert("End");
            return;
          }
          repeat(rnum);
        },
        error: function () {
          alert("NG");
        }
      });
    };

    var em = [];
    for(var p = 0; p < maxColnum; p++){
      em.push("");
    }

    $("#add_row").click(function () {
      alert("行を追加します");
      var body = handsontable.getData();
      var mr = body.length;
      for(var j = 0; j < 100; j++){
        body[mr + j] = em;
      }
      handsontable.loadData(body);
      handsontable.render();
    });

    $("#delete_data").click(function () {

      var myData = {data: "delete"};

      $.ajax({
        url: "/products/delete",
        type: "POST",
        data: myData,
        dataType: "json",
        success: function () {
          location.reload();
          alert("削除成功");

        },
        error: function () {
          alert("NG");
        }
      });
    });

    $("#csv_download").click(function () {
      var array_data = handsontable.getData();
      // BOM の用意（文字化け対策）
      var bom = new Uint8Array([0xEF, 0xBB, 0xBF]);
      // CSV データの用意
      var csv_data = array_data.map(function(l){return l.join(',')}).join('\r\n');
      var blob = new Blob([bom, csv_data], { type: 'text/csv' });
      var url = (window.URL || window.webkitURL).createObjectURL(blob);
      var a = document.getElementById('downloader');
      a.download = 'data.csv';
      a.href = url;
      // ダウンロードリンクをクリックする
      $('#downloader')[0].click();
    });

  });
</script>

app/views/products/setup.html.erb
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-8 col-md-10">
      <h3>ツールの設定</h3>
      <div class="col-lg-6">
        <%= form_for(@account, {url: products_setup_path, method: 'post'}) do |f| %>
          <p class="lead">利益計算の設定</p>
          <div class="form-group">
            <%= f.label :profit_rate, "新品利益率" %>
            <%= f.text_field :profit_rate, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :used_profit_rate, "中古利益率" %>
            <%= f.text_field :used_profit_rate, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :shipping, "送料" %>
            <%= f.text_field :shipping, class: 'form-control'  %>
          </div>
          <div class="actions">
            <%= f.submit "設定する", {id: "setup_btn", onClick: 'alert("更新しました")'} %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>